<?php
// ------------------------------------------------------------------------- //
//                           MS-WEATHER for Xoops                            //
//                              Version:  1.2                                //
//***************************************************************************//
// MS-Weather:                                                               //
// v1.2  28/01/2004 FOR XOOPS v2                                             //
// Ported by: Sylvain B. (sylvain@123rando.com)                              //
// http://123rando.com                                                       //
//                                                                           //
//---------------------------------------------------------------------------//
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//---------------------------------------------------------------------------//

$modversion['name'] = 'MS-Weather';
$modversion['version'] = '1.4';
$modversion['description'] = _MS_WEATHER_DESC;
$modversion['credits'] = 'Maty Scripts<br>webmaster@matyscripts.com';
$modversion['author'] = 'Ecris pour Xoops<br>par sylvain B.<br>http://123rando.com <br>Original script http://www.matyscripts.com';
$modversion['license'] = 'GNU/GPL';
$modversion['official'] = 0;
$modversion['image'] = 'images/msweather.jpg';
$modversion['dirname'] = 'ms_weather';

// Admin things
//$modversion['hasAdmin'] = 1;
//$modversion['adminindex'] = "admin/index.php";

// Blocks
$modversion['blocks'][1]['file'] = 'block-MS-Weather.php';
$modversion['blocks'][1]['name'] = _MS_WEATHER_BLOCK;
$modversion['blocks'][1]['show_func'] = 'disp_block_msweather';
$modversion['blocks'][1]['description'] = 'Display weather in a block';

// Menu
$modversion['hasMain'] = 1;

// Templates

$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/msweatheradmin.php';
$modversion['adminmenu'] = 'admin/menu.php';
// Search

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'msweather';

?>
